/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FunRouteImport } from './routes/fun'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ApiLettersRouteImport } from './routes/api/letters'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiPhotosRouteImport } from './routes/api/photos'
import { Route as ApiSongsRouteImport } from './routes/api/songs'
import { Route as ApiTimelineRouteImport } from './routes/api/timeline'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiVideosRouteImport } from './routes/api/videos'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth.logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth.session'
import { Route as ApiFunStagesRouteImport } from './routes/api/fun.stages'
import { Route as ApiLettersIdRouteImport } from './routes/api/letters.$id'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media.upload'
import { Route as ApiMediaUrlRouteImport } from './routes/api/media.url'
import { Route as ApiPhotosIdRouteImport } from './routes/api/photos.$id'
import { Route as ApiSongsIdRouteImport } from './routes/api/songs.$id'
import { Route as ApiTimelineIdRouteImport } from './routes/api/timeline.$id'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiVideosIdRouteImport } from './routes/api/videos.$id'
import { Route as ApiMediaEditIdRouteImport } from './routes/api/media.edit.$id'
import { Route as ApiMediaFileFileIdRouteImport } from './routes/api/media.file.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FunRoute = FunRouteImport.update({
  id: '/fun',
  path: '/fun',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLettersRoute = ApiLettersRouteImport.update({
  id: '/api/letters',
  path: '/api/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosRoute = ApiPhotosRouteImport.update({
  id: '/api/photos',
  path: '/api/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSongsRoute = ApiSongsRouteImport.update({
  id: '/api/songs',
  path: '/api/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimelineRoute = ApiTimelineRouteImport.update({
  id: '/api/timeline',
  path: '/api/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosRoute = ApiVideosRouteImport.update({
  id: '/api/videos',
  path: '/api/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFunStagesRoute = ApiFunStagesRouteImport.update({
  id: '/api/fun/stages',
  path: '/api/fun/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLettersIdRoute = ApiLettersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLettersRoute,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiMediaUrlRoute = ApiMediaUrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiPhotosIdRoute = ApiPhotosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPhotosRoute,
} as any)
const ApiSongsIdRoute = ApiSongsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSongsRoute,
} as any)
const ApiTimelineIdRoute = ApiTimelineIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTimelineRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiVideosIdRoute = ApiVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVideosRoute,
} as any)
const ApiMediaEditIdRoute = ApiMediaEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ApiMediaRoute,
} as any)
const ApiMediaFileFileIdRoute = ApiMediaFileFileIdRouteImport.update({
  id: '/file/$fileId',
  path: '/file/$fileId',
  getParentRoute: () => ApiMediaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fun': typeof FunRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/songs': typeof SongsRoute
  '/timeline': typeof TimelineRoute
  '/videos': typeof VideosRoute
  '/api/letters': typeof ApiLettersRouteWithChildren
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/photos': typeof ApiPhotosRouteWithChildren
  '/api/songs': typeof ApiSongsRouteWithChildren
  '/api/timeline': typeof ApiTimelineRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/videos': typeof ApiVideosRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/fun/stages': typeof ApiFunStagesRoute
  '/api/letters/$id': typeof ApiLettersIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/media/url': typeof ApiMediaUrlRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
  '/api/songs/$id': typeof ApiSongsIdRoute
  '/api/timeline/$id': typeof ApiTimelineIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/videos/$id': typeof ApiVideosIdRoute
  '/api/media/edit/$id': typeof ApiMediaEditIdRoute
  '/api/media/file/$fileId': typeof ApiMediaFileFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fun': typeof FunRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/songs': typeof SongsRoute
  '/timeline': typeof TimelineRoute
  '/videos': typeof VideosRoute
  '/api/letters': typeof ApiLettersRouteWithChildren
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/photos': typeof ApiPhotosRouteWithChildren
  '/api/songs': typeof ApiSongsRouteWithChildren
  '/api/timeline': typeof ApiTimelineRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/videos': typeof ApiVideosRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/fun/stages': typeof ApiFunStagesRoute
  '/api/letters/$id': typeof ApiLettersIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/media/url': typeof ApiMediaUrlRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
  '/api/songs/$id': typeof ApiSongsIdRoute
  '/api/timeline/$id': typeof ApiTimelineIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/videos/$id': typeof ApiVideosIdRoute
  '/api/media/edit/$id': typeof ApiMediaEditIdRoute
  '/api/media/file/$fileId': typeof ApiMediaFileFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fun': typeof FunRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/photos': typeof PhotosRoute
  '/songs': typeof SongsRoute
  '/timeline': typeof TimelineRoute
  '/videos': typeof VideosRoute
  '/api/letters': typeof ApiLettersRouteWithChildren
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/photos': typeof ApiPhotosRouteWithChildren
  '/api/songs': typeof ApiSongsRouteWithChildren
  '/api/timeline': typeof ApiTimelineRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/videos': typeof ApiVideosRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/fun/stages': typeof ApiFunStagesRoute
  '/api/letters/$id': typeof ApiLettersIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/media/url': typeof ApiMediaUrlRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
  '/api/songs/$id': typeof ApiSongsIdRoute
  '/api/timeline/$id': typeof ApiTimelineIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/videos/$id': typeof ApiVideosIdRoute
  '/api/media/edit/$id': typeof ApiMediaEditIdRoute
  '/api/media/file/$fileId': typeof ApiMediaFileFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fun'
    | '/letters'
    | '/login'
    | '/photos'
    | '/songs'
    | '/timeline'
    | '/videos'
    | '/api/letters'
    | '/api/media'
    | '/api/photos'
    | '/api/songs'
    | '/api/timeline'
    | '/api/users'
    | '/api/videos'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/fun/stages'
    | '/api/letters/$id'
    | '/api/media/$id'
    | '/api/media/upload'
    | '/api/media/url'
    | '/api/photos/$id'
    | '/api/songs/$id'
    | '/api/timeline/$id'
    | '/api/users/$id'
    | '/api/videos/$id'
    | '/api/media/edit/$id'
    | '/api/media/file/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/fun'
    | '/letters'
    | '/login'
    | '/photos'
    | '/songs'
    | '/timeline'
    | '/videos'
    | '/api/letters'
    | '/api/media'
    | '/api/photos'
    | '/api/songs'
    | '/api/timeline'
    | '/api/users'
    | '/api/videos'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/fun/stages'
    | '/api/letters/$id'
    | '/api/media/$id'
    | '/api/media/upload'
    | '/api/media/url'
    | '/api/photos/$id'
    | '/api/songs/$id'
    | '/api/timeline/$id'
    | '/api/users/$id'
    | '/api/videos/$id'
    | '/api/media/edit/$id'
    | '/api/media/file/$fileId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/fun'
    | '/letters'
    | '/login'
    | '/photos'
    | '/songs'
    | '/timeline'
    | '/videos'
    | '/api/letters'
    | '/api/media'
    | '/api/photos'
    | '/api/songs'
    | '/api/timeline'
    | '/api/users'
    | '/api/videos'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/fun/stages'
    | '/api/letters/$id'
    | '/api/media/$id'
    | '/api/media/upload'
    | '/api/media/url'
    | '/api/photos/$id'
    | '/api/songs/$id'
    | '/api/timeline/$id'
    | '/api/users/$id'
    | '/api/videos/$id'
    | '/api/media/edit/$id'
    | '/api/media/file/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FunRoute: typeof FunRoute
  LettersRoute: typeof LettersRoute
  LoginRoute: typeof LoginRoute
  PhotosRoute: typeof PhotosRoute
  SongsRoute: typeof SongsRoute
  TimelineRoute: typeof TimelineRoute
  VideosRoute: typeof VideosRoute
  ApiLettersRoute: typeof ApiLettersRouteWithChildren
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
  ApiPhotosRoute: typeof ApiPhotosRouteWithChildren
  ApiSongsRoute: typeof ApiSongsRouteWithChildren
  ApiTimelineRoute: typeof ApiTimelineRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiVideosRoute: typeof ApiVideosRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiFunStagesRoute: typeof ApiFunStagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun': {
      id: '/fun'
      path: '/fun'
      fullPath: '/fun'
      preLoaderRoute: typeof FunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/letters': {
      id: '/api/letters'
      path: '/api/letters'
      fullPath: '/api/letters'
      preLoaderRoute: typeof ApiLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos': {
      id: '/api/photos'
      path: '/api/photos'
      fullPath: '/api/photos'
      preLoaderRoute: typeof ApiPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/songs': {
      id: '/api/songs'
      path: '/api/songs'
      fullPath: '/api/songs'
      preLoaderRoute: typeof ApiSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/timeline': {
      id: '/api/timeline'
      path: '/api/timeline'
      fullPath: '/api/timeline'
      preLoaderRoute: typeof ApiTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos': {
      id: '/api/videos'
      path: '/api/videos'
      fullPath: '/api/videos'
      preLoaderRoute: typeof ApiVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fun/stages': {
      id: '/api/fun/stages'
      path: '/api/fun/stages'
      fullPath: '/api/fun/stages'
      preLoaderRoute: typeof ApiFunStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/letters/$id': {
      id: '/api/letters/$id'
      path: '/$id'
      fullPath: '/api/letters/$id'
      preLoaderRoute: typeof ApiLettersIdRouteImport
      parentRoute: typeof ApiLettersRoute
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/media/url': {
      id: '/api/media/url'
      path: '/url'
      fullPath: '/api/media/url'
      preLoaderRoute: typeof ApiMediaUrlRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/photos/$id': {
      id: '/api/photos/$id'
      path: '/$id'
      fullPath: '/api/photos/$id'
      preLoaderRoute: typeof ApiPhotosIdRouteImport
      parentRoute: typeof ApiPhotosRoute
    }
    '/api/songs/$id': {
      id: '/api/songs/$id'
      path: '/$id'
      fullPath: '/api/songs/$id'
      preLoaderRoute: typeof ApiSongsIdRouteImport
      parentRoute: typeof ApiSongsRoute
    }
    '/api/timeline/$id': {
      id: '/api/timeline/$id'
      path: '/$id'
      fullPath: '/api/timeline/$id'
      preLoaderRoute: typeof ApiTimelineIdRouteImport
      parentRoute: typeof ApiTimelineRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/videos/$id': {
      id: '/api/videos/$id'
      path: '/$id'
      fullPath: '/api/videos/$id'
      preLoaderRoute: typeof ApiVideosIdRouteImport
      parentRoute: typeof ApiVideosRoute
    }
    '/api/media/edit/$id': {
      id: '/api/media/edit/$id'
      path: '/edit/$id'
      fullPath: '/api/media/edit/$id'
      preLoaderRoute: typeof ApiMediaEditIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/api/media/file/$fileId': {
      id: '/api/media/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/api/media/file/$fileId'
      preLoaderRoute: typeof ApiMediaFileFileIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
  }
}

interface ApiLettersRouteChildren {
  ApiLettersIdRoute: typeof ApiLettersIdRoute
}

const ApiLettersRouteChildren: ApiLettersRouteChildren = {
  ApiLettersIdRoute: ApiLettersIdRoute,
}

const ApiLettersRouteWithChildren = ApiLettersRoute._addFileChildren(
  ApiLettersRouteChildren,
)

interface ApiMediaRouteChildren {
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiMediaUrlRoute: typeof ApiMediaUrlRoute
  ApiMediaEditIdRoute: typeof ApiMediaEditIdRoute
  ApiMediaFileFileIdRoute: typeof ApiMediaFileFileIdRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiMediaUrlRoute: ApiMediaUrlRoute,
  ApiMediaEditIdRoute: ApiMediaEditIdRoute,
  ApiMediaFileFileIdRoute: ApiMediaFileFileIdRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

interface ApiPhotosRouteChildren {
  ApiPhotosIdRoute: typeof ApiPhotosIdRoute
}

const ApiPhotosRouteChildren: ApiPhotosRouteChildren = {
  ApiPhotosIdRoute: ApiPhotosIdRoute,
}

const ApiPhotosRouteWithChildren = ApiPhotosRoute._addFileChildren(
  ApiPhotosRouteChildren,
)

interface ApiSongsRouteChildren {
  ApiSongsIdRoute: typeof ApiSongsIdRoute
}

const ApiSongsRouteChildren: ApiSongsRouteChildren = {
  ApiSongsIdRoute: ApiSongsIdRoute,
}

const ApiSongsRouteWithChildren = ApiSongsRoute._addFileChildren(
  ApiSongsRouteChildren,
)

interface ApiTimelineRouteChildren {
  ApiTimelineIdRoute: typeof ApiTimelineIdRoute
}

const ApiTimelineRouteChildren: ApiTimelineRouteChildren = {
  ApiTimelineIdRoute: ApiTimelineIdRoute,
}

const ApiTimelineRouteWithChildren = ApiTimelineRoute._addFileChildren(
  ApiTimelineRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiVideosRouteChildren {
  ApiVideosIdRoute: typeof ApiVideosIdRoute
}

const ApiVideosRouteChildren: ApiVideosRouteChildren = {
  ApiVideosIdRoute: ApiVideosIdRoute,
}

const ApiVideosRouteWithChildren = ApiVideosRoute._addFileChildren(
  ApiVideosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FunRoute: FunRoute,
  LettersRoute: LettersRoute,
  LoginRoute: LoginRoute,
  PhotosRoute: PhotosRoute,
  SongsRoute: SongsRoute,
  TimelineRoute: TimelineRoute,
  VideosRoute: VideosRoute,
  ApiLettersRoute: ApiLettersRouteWithChildren,
  ApiMediaRoute: ApiMediaRouteWithChildren,
  ApiPhotosRoute: ApiPhotosRouteWithChildren,
  ApiSongsRoute: ApiSongsRouteWithChildren,
  ApiTimelineRoute: ApiTimelineRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiVideosRoute: ApiVideosRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiFunStagesRoute: ApiFunStagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
